Settings:
  mainLobbyLocation:


Games:
  Types:
    BATTLE_ROYALE:
      chest-loot-t1:
        weight: 70
        items:
          - "STONE_SWORD:1"
          - "STONE_AXE:1"
          - "SNOWBALL:2"
          - "SNOWBALL:4"
          - "APPLE:4"
          - "APPLE:6"
          - "GOLDEN_APPLE:1"
          - "GOLDEN_APPLE:2"
          - "CHAINMAIL_BOOTS:1"
          - "CHAINMAIL_HELMET:1"
          - "CHAINMAIL_LEGGINGS:1"
      chest-loot-t2:
        weight: 40
        items:
          - "IRON_SWORD:1"
          - "IRON_AXE:1"
          - "SNOWBALL:4"
          - "APPLE:8"
          - "COOKED_BEEF:2"
          - "GOLDEN_APPLE:2"
          - "BOW:1"
          - "ARROW:4"
          - "ARROW:4"
          - "IRON_BOOTS:1"
          - "IRON_HELMET:1"
          - "CHAINMAIL_LEGGINGS:1"
          - "IRON_LEGGINGS:1"
          - "CHAINMAIL_CHESTPLATE:1"
      chest-loot-t3:
        weight: 20
        items:
          - "IRON_SWORD:1"
          - "GOLDEN_SWORD:1"
          - "IRON_AXE:1"
          - "APPLE:8"
          - "BOW:1"
          - "COOKED_BEEF:4"
          - "GOLDEN_APPLE:2"
          - "GOLDEN_APPLE:2"
          - "IRON_BOOTS:1"
          - "ARROW:4"
          - "ARROW:8"
          - "ARROW:8"
          - "IRON_HELMET:1"
          - "IRON_LEGGINGS:1"
          - "IRON_CHESTPLATE:1"
          - "DIAMOND_HELMET:1"
          - "DIAMOND_BOOTS:1"
      chest-loot-t4:
        weight: 10
        items:
          - "IRON_SWORD:1"
          - "DIAMOND_SWORD:1"
          - "IRON_AXE:1"
          - "DIAMOND_AXE:1"
          - "ARROW:8"
          - "ARROW:8"
          - "ARROW:16"
          - "COOKED_BEEF:6"
          - "GOLDEN_APPLE:2"
          - "GOLDEN_APPLE:2"
          - "GOLDEN_APPLE:2"
          - "IRON_BOOTS:1"
          - "IRON_HELMET:1"
          - "IRON_LEGGINGS:1"
          - "IRON_CHESTPLATE:1"
          - "IRON_CHESTPLATE:1"
          - "DIAMOND_HELMET:1"
          - "DIAMOND_HELMET:1"
          - "DIAMOND_BOOTS:1"
          - "DIAMOND_BOOTS:1"
          - "DIAMOND_LEGGINGS:1"
          - "DIAMOND_LEGGINGS:1"
          - "DIAMOND_CHESTPLATE:1"
