Settings:
  mainLobbyLocation:


Games:
  Types:
    BATTLE_ROYALE:
      chest-loot-t1:
        weight: 60
        items:
          - "STONE_SWORD:1"
          - "STONE_AXE:1"
          - "IRON_AXE:1"
          - "APPLE:4"
          - "APPLE:4"
          - "IRON_BOOTS:1"
          - "IRON_HELMET:1"
          - "CHAINMAIL_LEGGINGS:1"
          - "CHAINMAIL_CHESTPLATE:1"
          - "IRON_HELMET:1"
          - "ARROW:2"
          - "ARROW:2"
      chest-loot-t2:
        weight: 15
        items:
          - "IRON_SWORD:1"
          - "IRON_AXE:1"
          - "APPLE:4"
          - "COOKED_BEEF:2"
          - "COOKED_BEEF:2"
          - "GOLDEN_APPLE:1"
          - "BOW:1"
          - "CROSSBOW:1"
          - "ARROW:4"
          - "ARROW:4"
          - "DIAMOND_BOOTS:1"
          - "DIAMOND_HELMET:1"
          - "IRON_LEGGINGS:1"
          - "IRON_CHESTPLATE:1"
      chest-loot-t3:
        weight: 15
        items:
          - "IRON_SWORD:1"
          - "GOLDEN_SWORD:1"
          - "GOLDEN_AXE:1"
          - "IRON_AXE:1"
          - "APPLE:8"
          - "BOW:1"
          - "CROSSBOW:1"
          - "SHIELD:1"
          - "COOKED_BEEF:4"
          - "GOLDEN_APPLE:2"
          - "IRON_BOOTS:1"
          - "ARROW:4"
          - "ARROW:8"
          - "ARROW:8"
          - "DIAMOND_BOOTS:1"
          - "DIAMOND_HELMET:1"
          - "DIAMOND_LEGGINGS:1"
          - "DIAMOND_CHESTPLATE:1"
      chest-loot-t4:
        weight: 10
        items:
          - "DIAMOND_SWORD:1"
          - "IRON_AXE:1"
          - "DIAMOND_AXE:1"
          - "SHIELD:1"
          - "ARROW:8"
          - "ARROW:16"
          - "CROSSBOW:1"
          - "ENDER_PEARL:1"
          - "COOKED_BEEF:6"
          - "COOKED_BEEF:6"
          - "GOLDEN_APPLE:2"
          - "DIAMOND_BOOTS:1"
          - "DIAMOND_HELMET:1"
          - "DIAMOND_LEGGINGS:1"
          - "DIAMOND_CHESTPLATE:1"
          - "NETHERITE_BOOTS:1"
